kind: Namespace
apiVersion: v1
metadata:
  name: sample-app
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-app
  namespace: sample-app
spec:
  selector:
    matchLabels:
      app: sample-app
  replicas: 1
  template:
    metadata:
      name: sample-app
      labels:
        app: sample-app
    spec:
      containers:
      - name: nginx
        image: alanrenouf/docker-nginx-hello-keswick
        ports:
        - containerPort: 80
      imagePullSecrets:
      - name: dockerhub-creds
---
apiVersion: v1
kind: Service
metadata:
  name: sample-app
  namespace: sample-app
spec:
  type: NodePort
  selector:
    app: sample-app
  ports:
    - port: 80
      nodePort: 30888
